const AppConstants = {
    MIN_DEPOSIT_AMOUNT: 500,
    MAX_DEPOSIT_AMOUNT: 50000,
    MIN_WITHDRAW_AMOUNT: 1000,
    MAX_WITHDRAW_AMOUNT: 25000,
    MAX_ACCOUNT_BALANCE: 100000,
    MIN_ACCOUNT_BALANCE: 0,
}

module.exports = AppConstants;